name: Push-to-EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TERRAFORM_KEY }}
          REMOTE_HOST: ${{ vars.HOST_DNS }}
          REMOTE_USER: ${{ vars.USERNAME }}
          TARGET: ${{ vars.TARGET_DIR }}

      - name: Run commands on the server
        run: |
          echo $TERRAFORM_KEY > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem ${{ vars.USERNAME }}@${{ vars.HOST_DNS }} "sudo rm -rf /usr/share/nginx/html/* && sudo mv -f   ${{ vars.HOST_DNS }}/* /usr/share/nginx/html/."
